QCD1:
  diann_version: "1.9.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-1.9.2.img"  
  config_file: "diann_configs/diann_qcd1.cfg"
  parser_version: "tsv"
  executable: "/diann-1.9.2/diann-linux"
  description: "BSA DIA quality control"
  requiresConversion: true
  
QCD2:
  diann_version: "1.9.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-1.9.2.img"  
  config_file: "diann_configs/diann_qcd2.cfg"
  parser_version: "tsv"
  executable: "/diann-1.9.2/diann-linux"
  description: "HELA DIA quality control"
  requiresConversion: true                                            

NK:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_nk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome DIA quantification (current)"
  requiresConversion: false

MK:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_nk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome DIA quantification (old)"
  requiresConversion: false                                           

LD:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_nk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Chromatin-bound proteome"
  requiresConversion: false   

ME:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_nk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome label-free quantification in exosomes (DIA) - Proteome"
  requiresConversion: false   

MS:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_nk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome label-free quantification in secretome (DIA)"
  requiresConversion: false  

NY:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img"  
  config_file: "diann_configs/diann_nk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Phosphoproteome label-free quantification (DIA)"
  requiresConversion: false  

BK:
  diann_version: "2.3.2"
  container: "/users/pr/proteomics/mygit/atlas-imgs/diann-2.3.2.img" 
  config_file: "diann_configs/diann_bk.cfg"
  parser_version: "parquet"
  executable: "/opt/diann/diann-2.3.2/diann-linux"
  description: "Proteome DIA quantification (Bruker)"
  requiresConversion: false                                            